baseURL = "http://gregoriustanley.com/"
languageCode = "en-us"
title = "Stanley"
theme = "anatole"

[menu]
    [[menu.main]]
    name = "about me"
    identifier = "about"
    weight = 100
    url = "/about/"

    [[menu.main]]
    name = "blog"
    identifier = "blog"
    weight = 101
    url = "/blog/"

    [[menu.main]]
    name = "books"
    identifier = "books"
    weight = 102
    url = "/books/"

    [[menu.main]]
    name = "experience"
    identifier = "experience"
    weight = 103
    url = "/experience/"

    [[menu.main]]
    name = "project"
    identifier = "project"
    weight = 104
    url = "/project/"

    [[menu.main]]
    name = "resume"
    identifier = "resume"
    weight = 105
    url = "/resume/"

    [[menu.main]]
    name = "contact me"
    identifier = "contact"
    weight = 106
    url = "/contact/"

[params]
    title = 'hi, Stanley here!'
    author = "Stanley 2021"
    description = "<h4><i>philomath</i> — lover of learning</h4>"
    profilePicture = "images/profile.jpg"
    copyright = " | Based on Anatole theme"
    contentratio = 0.7
    readMore = true

    [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/gregoriustanley/"

    [[params.socialIcons]]
    icon = "fab fa-instagram"
    title = "Instagram"
    url = "https://www.instagram.com/gregoriustanley/"

    [[params.socialIcons]]
    icon = "fab fa-github"
    title = "Github"
    url = "https://github.com/gregoriustanleyy"

    [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/gregoriustanley"

    [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "Email"
    url = "mailto:gstanleytejakusuma@gmail.com"