baseURL = "http://gregoriustanley.com/"
languageCode = "en-us"
title = "Stanley"
theme = "anatole"

[menu]
    [[menu.main]]
    name = "About"
    identifier = "about"
    weight = 100
    url = "/about/"

    [[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 101
    url = "/blog/"

    [[menu.main]]
    name = "Books"
    identifier = "books"
    weight = 102
    url = "/books/"

    [[menu.main]]
    name = "Experience"
    identifier = "experience"
    weight = 103
    url = "/experience/"

    [[menu.main]]
    name = "Resume"
    identifier = "resume"
    weight = 104
    url = "/resume/"

    [[menu.main]]
    name = "Contact Me"
    identifier = "contact"
    weight = 105
    url = "/contact/"

[params]
    title = "Hi, Stanley here!"
    author = "Stanley 2021"
    description = """
                <h4><i>philomath</i> — lover of learning</h4>
                I'm a <b>data scientist</b> student at Purdue university with Business Economics. I have profound interest in the financial sector and data field. Currently, I am in pursuit of specifically <b>data analytics application into Financial Statements</b>.
                """
    profilePicture = "images/profile.jpg"
    copyright = " | Based on Anatole theme"

    [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/gregoriustanley/"

    [[params.socialIcons]]
    icon = "fab fa-instagram"
    title = "Instagram"
    url = "https://www.instagram.com/gregoriustanley/"

    [[params.socialIcons]]
    icon = "fab fa-github"
    title = "Github"
    url = "https://github.com/gregoriustanleyy"

    [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/gregoriustanley"

    [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "Email"
    url = "mailto:gstanleytejakusuma@gmail.com"